config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root               'posts#index'
  get 'about'         => 'static_pages#about'
  get 'contact'       => 'static_pages#contact'
  get 'signup'        => 'users#new'

  get 'login'         => 'sessions#new'
  post 'login'        => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'

  get 'posts/pending'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    member do
      get :publish
      get :unpublish
    end
  end
  resources :sections
  resources :labels
  resources :static_pages
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/comments_controller.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CommentsController < ApplicationController
  before_action :logged_in_user, only: :create
  before_action :post_published, only: :create

  def index
    @post = Post.find(params[:post_id])
    redirect_to @post
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "Comment added"
      redirect_to @post
    else
      @sections = @post.sections
      @comments = @post.comments.paginate(page: params[:page])
      render 'posts/show' # todo: autoscroll to comment form
    end
  end

  def destroy
  end


  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def post_published
      post = Post.find(params[:post_id])
      unless post.published
        flash[:error] = "Publish the post before adding comments"
        redirect_to post
      end
    end
end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <div class="row-fluid">
      <div class="text-sm-right col-sm-4">
        <div class="author">
          <% @author = User.find_by(id: comment.user_id) %>
          <% if @author %>
            <%= link_to @author.name, user_path(comment.user_id) %>
          <% else %>
            <span class="missing_user">user deleted</span>
          <% end %>

        </div>
        <div class="timestamp">
          <%= time_ago_in_words(comment.created_at).gsub('about','') %> ago
        </div>
      </div>
      <div class="col-sm-8">
        <%= simple_format comment.body %>
      </div>
  </div>
</li>

app/views/comments/_form.html.erb
<%= form_for [ @post, @comment ] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="comment-form centered">
    <% if logged_in? %>
      <span>
        <%= f.label :body, 'Post a comment' %><br/>
        <%= f.text_area :body, class: 'form-control field-group textarea' %>
      </span>
      <span>
        <%= f.submit 'Submit', class: "btn btn-primary" %>
      </span>
    <% else %>
      <p class="text-center">
        <%= link_to "Log in", login_path %>
        or
        <%= link_to "Sign up", signup_path %>
        to add a comment
      </p>
    <% end %>
  </div>
<% end %>