config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root               'posts#index'
  get 'about'         => 'static_pages#about'
  get 'contact'       => 'static_pages#contact'
  get 'signup'        => 'users#new'

  get 'login'         => 'sessions#new'
  post 'login'        => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'

  get 'posts/pending'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    member do
      get :publish
      get :unpublish
    end
  end
  resources :sections
  resources :labels
  resources :static_pages
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  title           :string
#  picture         :string
#  body            :text
#  picture_caption :string
#  published_at    :datetime
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :sections, dependent: :destroy
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :comments, dependent: :destroy

  mount_uploader :picture, PictureUploader

  accepts_nested_attributes_for :sections, allow_destroy: true, reject_if: :all_blank

  scope :get_published, -> { where("published_at IS NOT NULL") }
  scope :get_unpublished, -> { where(published_at: nil) }
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  self.per_page = 8

  def label_list
    labels.join(", ")
  end

  def label_list=(labels_string)
    label_names = labels_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_labels = label_names.collect { |name| Label.find_or_create_by(name: name) }
    self.labels = new_or_found_labels
  end

  def published
    self.published_at.nil? ? false : true
  end

  def published?
    self.published_at.nil? ? false : true
  end

  def self.search(query)
    # add some query method in here on labels, sections, title, body...  
  end
end

app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  title           :string
#  picture         :string
#  body            :text
#  picture_caption :string
#  published_at    :datetime
#

class PostsController < ApplicationController
  before_action :admin_only, except: [:index, :show]
  before_action :logged_in_user, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update]

  def index
    @posts = Post.get_published.paginate(page: params[:page]).includes(:labels)
  end

  def pending
    @posts = Post.get_unpublished.paginate(page: params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @sections = @post.sections
    @comments = @post.comments.paginate(page: params[:page])
    @comment = @post.comments.build
    admin_only unless @post.published?
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to @post
    else
      render 'posts/new'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"
    redirect_to root_url
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def publish
    @post = Post.find(params[:id])
    @post.update_attribute(:published_at, Time.zone.now)
    flash[:success] = "Post published"
    redirect_to @post
  end

  def unpublish
    @post = Post.find(params[:id])
    @post.update_attribute(:published_at, nil)
    flash[:success] = "Post unpublished"
    redirect_to @post
  end

  private
    def post_params
      params.require(:post).permit( :title, :body, :picture, :picture_caption, :label_list,
            sections_attributes: [:id, :title, :body, :picture, :picture_caption, :_destroy])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  title           :string
#  picture         :string
#  body            :text
#  picture_caption :string
#  published_at    :datetime
#

module PostsHelper
end

app/views/posts/_form.html.erb
<div class="post">
  <%= form_for(@post, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :body %>
    <%= f.text_area :body, rows: 5, class: "textarea form-control" %>

    <%= f.label :picture, 'Primary image' %>
    <% if @post.picture? %>
      <div>
        <%= image_tag @post.picture.url(:medium), class: "img" %>
      </div>
    <% end %>
    <%= f.text_field :picture_caption,
          placeholder: "image caption (optional)",
          class: 'form-control'%>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'field-group' %>
    </span>
    <div class="section">
      <%= f.fields_for :sections do |section| %>
        <div>
          <%= render 'section_fields', f: section %>
        </div>
      <% end %>
      <div id="add">
        <%= link_to_add_association 'add section', f, :sections %>
      </div>
    </div>

    <p>
      <%= f.label :label_list %>
      <%= f.text_field :label_list, class: 'form-control field-group' %>
    </p>


    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <div class="row-fluid">
    <figure class="<%= "col-sm-5" if post.picture? %>">
      <%= link_to image_tag(post.picture.url(:medium), class: "img"), post %>
    </figure>
    <div class="<%= post.picture? ? "col-sm-7 content" : "col-sm-12 content" %>">
      <span class="h2 title"><%= link_to post.title, post %></span>
      <% if post.published %>
        <span class="timestamp">
          <%= post.published_at.to_date.to_formatted_s :long %>
        </span>
      <% else %>
        <p class="unpublished row">--Unpublished--</p>
      <% end %>
        <div class="body">
          <%= sanitize RedCloth.new(post.body).to_html.truncate(255, separator: ' ') %>
        </div>
        <% if post.labels.any? %>
          <span class="labels text-right">
            <% post.labels.each do |label| %>
              <%= link_to label.name, label, class: "btn" %>
            <% end %>
          </span>
        <% end %>
      </span>
    </div>
  </div>
</li>

app/views/posts/_section_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls field-group">
    <%= f.label :section %>
    <%= f.text_field :title, class: 'form-control', placeholder: "section title (optional)" %>
    <%= f.text_area :body, rows: 5, class: 'textarea form-control', placeholder: "section body" %>
    <% if f.object.picture? %>
      <%= image_tag f.object.picture.url(:medium), class: "img" %>
    <% end %>
    <%= f.text_field :picture_caption,
          placeholder: "image caption (optional)",
          class: 'form-control'%>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'img-upload' %>
    </span>
    <%= link_to_remove_association "remove", f, class: 'admin-links field-group' %>
  </div>
</li>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit post') %>
<% provide(:button_text, 'Save') %>

<h1>Edit post</h1>

<div class="row">
  <div class="col-md-6 col-sm-8 col-lg-5 centered">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<% if @posts.current_page == 1 %>
<div class="jumbotron welcome">
  <div class="content col-md-10 col-lg-9 col-sm-11 centered">
    <h1>Welcome to <span class="logo">Rig</span></h1>
    <h2>Create.</h2>
  </div>
</div>
<% end %>

<div class="posts">
  <%= render 'shared/posts' %>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'New post') %>
<% provide(:button_text, 'Create post') %>

<h1>New post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/pending.html.erb
<% provide(:title, "Pending posts") %>

<% if logged_in? && current_user.admin? %>
  <div class="admin-links">
    <%= link_to "create post", new_post_path %>
  </div>
<% end %>

<h1 class="centered text-center">Pending posts</h1>

<div class="posts">
  <%= render 'shared/posts' %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="post">
  <% if logged_in? && current_user.admin? %>
    <div class="admin-links">
      <%= link_to "edit", edit_post_path(@post) %> |
      <% if @post.published %>
        <%= link_to "unpublish", [:unpublish, @post], data: {confirm: "You Sure?"} %>
      <% else %>
      <%= link_to "publish", [:publish, @post], data: {confirm: "You Sure?"} %>
      <% end %>
      | <%= link_to "delete", @post, method: :delete, data: {confirm: "You Sure?"} %>
    </div>
  <% end %>
  <figure class="image-container centered">
    <% if @post.picture? %>
      <%= link_to image_tag(@post.picture.url, class: "image"), @post.picture.url %>
      <figcaption class="text-center"><%= @post.picture_caption %></figcaption>
    <% end %>
  </figure>
  <div class="post-body centered">
    <header class="post-header">
      <h1><%= @post.title %></h1>
      <% if @post.published %>
        <span class="timestamp">
          <%= @post.published_at.to_date.to_formatted_s :long %>
        </span>
      <% else %>
        <p class="unpublished row">--Unpublished--</p>
      <% end %>
    </header>
    <div class="body"><%= RedCloth.new(@post.body).to_html.html_safe  %></div>
    <div class="sections"><%= render 'shared/sections' %></div>
    <footer class="centered">
      <span class="labels"><%= render 'shared/labels' %></span>
      <span class="float-right"><%= link_to "back to posts", root_url %></span>
    </footer>
  </div>

  <% if @post.published %>
    <div class="comments centered">
      <%= render 'shared/comments' %>
        <%= render partial: 'comments/form', id: "form" %>
    </div>
  <% end %>
</div>