config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root               'posts#index'
  get 'about'         => 'static_pages#about'
  get 'contact'       => 'static_pages#contact'
  get 'signup'        => 'users#new'

  get 'login'         => 'sessions#new'
  post 'login'        => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'

  get 'posts/pending'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    member do
      get :publish
      get :unpublish
    end
  end
  resources :sections
  resources :labels
  resources :static_pages
end

app/views/layouts/_footer.html.erb
<footer class="footer container-fluid navbar-default">
  <small>
    <!-- This is a footer -->
  </small>
  <nav class="navbar-right">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <%= link_to "Rig", root_path, id: "logo" %>
    <nav class="navbar-right">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% if admin_user? %>
            <li><%= link_to "Pending", posts_pending_path %></li>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class='btn-login'>
            <%= form_for(:session, url: login_path) do |f| %>
              <%= f.hidden_field :email, value: 'admin@rig.org' %>
              <%= f.hidden_field :password, value: 'password' %>
              <%= f.submit "Log in as admin", class: 'btn btn-primary' %>
            <% end %>
          </li>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name='theme-color' content='#d74d2f'>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>
  <body class="Site">
    <%= render 'layouts/header' %>
    <main class="Site-content">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <div class="container"><%= debug(params) if Rails.env.development? %></div>
  </body>
</html>